name: Slither Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install Modules
      run: npm install

    - name: Run Slither
      uses: crytic/slither-action@v0.2.0
      with:
        fail-on: none
